require 'plugins.telescope'.setup()
require 'plugins.treesitter'.setup()
require 'plugins.gitsigns'.setup()
require 'plugins.comment'.setup()
require 'plugins.pairs'.setup()
require 'plugins.lualine'.setup()
require 'plugins.codeium'.setup()
require 'plugins.coc'.setup()
