-- reload config
vim.keymap.set('n', '<leader>sr', ':source<CR>')

vim.keymap.set('n', 'р', ':norm h<CR>', { silent = true })
vim.keymap.set('n', '[', ':norm ~<CR>', { silent = true })
vim.keymap.set('n', 'о', ':norm j<CR>', { silent = true })
vim.keymap.set('n', 'л', ':norm k<CR>', { silent = true })
vim.keymap.set('n', 'д', ':norm l<CR>', { silent = true })
vim.keymap.set('n', 'щ', ':norm o<CR>', { silent = true })
vim.keymap.set('n', 'Щ', ':norm O<CR>', { silent = true })
vim.keymap.set('n', '<C-з>', ':norm <C-p><CR>', { silent = true })
vim.keymap.set('n', '<C-З>', ':norm <C-P><CR>', { silent = true })
vim.keymap.set('v', 'р', '<Left>')
vim.keymap.set('v', 'о', '<Down>')
vim.keymap.set('v', 'л', '<Up>')
vim.keymap.set('v', 'д', '<Right>')

vim.keymap.set('n', 'ф', 'a')
vim.keymap.set('n', 'Ф', 'A')
vim.keymap.set('n', 'ш', 'i')
vim.keymap.set('n', 'Ш', 'I')
vim.keymap.set('n', 'ц', ':norm w<CR>', { silent = true })
vim.keymap.set('n', 'у', ':norm e<CR>', { silent = true })
vim.keymap.set('n', 'и', ':norm b<CR>', { silent = true })
vim.keymap.set('n', 'м', ':norm v<CR>', { silent = true })
vim.keymap.set('n', 'М', ':norm <S-V><CR>', { silent = true })

vim.keymap.set('n', '<leader>w', ':update<CR>')
vim.keymap.set('n', '<leader>ц', ':update<CR>')
vim.keymap.set('n', '<leader>q', ':q<CR>')
vim.keymap.set('n', '<leader>й', ':q<CR>')

vim.keymap.set('n', '<leader>-', ':split<CR>')
vim.keymap.set('n', '<leader>|', ':vsplit<CR>')
vim.keymap.set('n', '<leader>/', ':vsplit<CR>')
vim.keymap.set('n', '<leader>h', ':noh<CR>')
vim.keymap.set('n', '<leader>р', ':noh<CR>')
vim.keymap.set('n', '<tab><tab>', ':tabn<CR>')
vim.keymap.set('n', '<S-tab><S-tab>', ':tabp<CR>')
vim.keymap.set('n', '<tab>t', ':tabnew<CR>:Oil<CR>')
vim.keymap.set('n', '<tab>е', ':tabnew<CR>:Oil<CR>')
vim.keymap.set('n', '<leader>co', ':copen<CR>')
vim.keymap.set('n', '<leader>cn', ':cn<CR>')
vim.keymap.set('n', '<leader>cp', ':cp<CR>')
vim.keymap.set('n', '<leader>cc', ':cclose<CR>')
vim.keymap.set('n', '<leader>cf', ':caddfile %<CR>')
